version: '{build}-{branch}'
image: Visual Studio 2017

skip_commits:
  files:
    - '**/*.md'

build_script:
- ps: .\build.ps1

after_build:
- ps: .\pack.ps1

artifacts:
- path: '**\artifacts\nuget\*.nupkg'
  name: NuGet
  
deploy:
- provider: NuGet
  api_key:
    secure: bjyBnS9X1isEB1mvrKkK2qGfvwyK1DT6thhYco93j6Dp0RuJlzHjvp5yiydhaM/c
  on:
    appveyor_repo_tag: true